import { BrainwaveBand, CognitiveStateConfig, SpecCategory, PipelineStep, UseCase } from '../types';

export const BRAINWAVE_BANDS: BrainwaveBand[] = [
  {
    id: 'delta',
    name: 'Delta',
    symbol: 'δ',
    rangeHz: '0.5 – 4.0 Hz',
    freqMin: 0.5,
    freqMax: 4.0,
    amplitudeMicrovolts: '20 – 200 µV',
    corticalState: 'Non-REM slow-wave sleep & autonomic reset',
    classificationRole: 'Fatigue accumulation marker & sleep stage ground truth',
    description: 'Slowest high-amplitude cortical oscillation generated predominantly in thalamocortical networks. Elevated awake delta signals neurological fatigue or severe attentional lapse.',
    signalPattern: 'Wide sinusoidal waves with slow sweeping peak-to-peak transitions'
  },
  {
    id: 'theta',
    name: 'Theta',
    symbol: 'θ',
    rangeHz: '4.0 – 8.0 Hz',
    freqMin: 4.0,
    freqMax: 8.0,
    amplitudeMicrovolts: '10 – 50 µV',
    corticalState: 'Working memory maintenance & hippocampal gating',
    classificationRole: 'Frontal midline theta (Fmθ) monitors active mental workload',
    description: 'Originates in medial prefrontal cortex and anterior cingulate. Increases during demanding arithmetic, spatial navigation, and sustained memory encoding.',
    signalPattern: 'Rhythmic medium-speed oscillation interspersed with intermittent bursts'
  },
  {
    id: 'alpha',
    name: 'Alpha',
    symbol: 'α',
    rangeHz: '8.0 – 13.0 Hz',
    freqMin: 8.0,
    freqMax: 13.0,
    amplitudeMicrovolts: '20 – 60 µV',
    corticalState: 'Alert relaxation, sensory gating, idle baseline',
    classificationRole: 'Frontal Alpha Asymmetry (FAA) reveals emotional valence and approach/avoidance',
    description: 'Prominent across occipital and parietal lobes when eyes are closed or senses are resting. Desynchronizes instantly (alpha suppression) during focused visual or cognitive tasks.',
    signalPattern: 'Classic regular spindle rhythms with clean sinusoidal symmetry'
  },
  {
    id: 'beta',
    name: 'Beta',
    symbol: 'β',
    rangeHz: '13.0 – 30.0 Hz',
    freqMin: 13.0,
    freqMax: 30.0,
    amplitudeMicrovolts: '5 – 30 µV',
    corticalState: 'Active conscious problem solving, motor control, vigilance',
    classificationRole: 'High-beta (22–30 Hz) corresponds to acute cognitive friction and somatic stress',
    description: 'Fast, lower-voltage activity dominant across frontal and central motor cortices during analytical processing. Elevated high-beta serves as a direct marker for sympathetic distress.',
    signalPattern: 'Dense, rapid jagged oscillations with variable low-amplitude envelopes'
  },
  {
    id: 'gamma',
    name: 'Gamma',
    symbol: 'γ',
    rangeHz: '30.0 – 100.0 Hz',
    freqMin: 30.0,
    freqMax: 100.0,
    amplitudeMicrovolts: '2 – 10 µV',
    corticalState: 'Cross-modal sensory binding & peak attentional coherence',
    classificationRole: 'Coherence index indicates instantaneous cortical integration and high focus',
    description: 'Ultra-fast oscillations generated by parvalbumin-positive interneurons. Essential for uniting disparate sensory perceptions into a cohesive conscious experience.',
    signalPattern: 'High-frequency low-microvolt ripple superimposed on slower carrier rhythms'
  }
];

export const COGNITIVE_PRESETS: CognitiveStateConfig[] = [
  {
    id: 'baseline',
    label: 'Resting Wakefulness (Eyes Open)',
    description: 'Balanced alpha baseline with standard frontocentral beta activity. Resting vigilance.',
    dominantBands: ['Alpha (10.2 Hz)', 'Low-Beta (15.4 Hz)'],
    metrics: {
      cognitiveLoad: 32,
      stressLevel: 18,
      valence: +0.45,
      signalSnr: 25.4
    }
  },
  {
    id: 'deep_focus',
    label: 'High Focus / Flow State',
    description: 'Marked alpha desynchronization, elevated frontal midline theta (Fmθ), and phase-locked gamma bursts.',
    dominantBands: ['Theta (6.4 Hz)', 'Gamma (38.5 Hz)'],
    metrics: {
      cognitiveLoad: 81,
      stressLevel: 26,
      valence: +0.68,
      signalSnr: 27.1
    }
  },
  {
    id: 'high_stress',
    label: 'Acute Cognitive Stress & Overload',
    description: 'Suppressed alpha, excessive asynchronous high-beta (24–29 Hz), right-frontal dominance (negative valence).',
    dominantBands: ['High-Beta (26.8 Hz)', 'Low-Alpha (8.2 Hz)'],
    metrics: {
      cognitiveLoad: 94,
      stressLevel: 88,
      valence: -0.62,
      signalSnr: 21.8
    }
  },
  {
    id: 'deep_rest',
    label: 'Deep Meditation / Non-REM Rest',
    description: 'Large synchronized slow-wave theta and delta progression, low muscle artifact, deep calm.',
    dominantBands: ['Delta (2.1 Hz)', 'Theta (5.2 Hz)'],
    metrics: {
      cognitiveLoad: 11,
      stressLevel: 8,
      valence: +0.82,
      signalSnr: 28.5
    }
  }
];

export const PIPELINE_STEPS: PipelineStep[] = [
  {
    step: '01',
    title: 'Wear & 3-Electrode Seating',
    subtitle: 'Zero-preparation dry-contact acquisition',
    description: 'Place the lightweight CAD-balanced headband over the forehead. Ergonomic Ag/AgCl dry elastomer electrodes self-align against the prefrontal cortex (Fp1, Fp2) with an active earclip reference without conductive gel or skin abrasion.',
    technicalDetails: [
      '3-Electrode clinical montage: Fp1 (left frontal), Fp2 (right frontal), REF/GND (earclip)',
      'Dual active earclip Common Mode Sense (CMS) & Driven Right Leg (DRL)',
      'Continuous hardware impedance monitoring (< 10 kΩ threshold verification)'
    ]
  },
  {
    step: '02',
    title: 'Raw EEG Signal Acquisition',
    subtitle: '24-bit delta-sigma continuous sampling',
    description: 'Biomedical-grade front-end converters continuously digitize cortical potentials at 250–500 samples per second. Hardware common-mode rejection isolates sub-microvolt brain potentials from environmental 50/60 Hz grid noise.',
    technicalDetails: [
      '24-bit low-noise Delta-Sigma ADC with 0.8 µV RMS noise floor (0.1–50 Hz)',
      '112 dB Common Mode Rejection Ratio (CMRR)',
      'Hardware anti-aliasing & analog bandpass filter (0.1 Hz to 100 Hz)'
    ]
  },
  {
    step: '03',
    title: 'Global Host Ingestion & Cloud Telemetry',
    subtitle: 'Real-time worldwide telemetry link to web dashboard',
    description: 'The physical headband communicates via WiFi, cellular, or local serial bridge (Python or ESP32) directly to this global host web server. The global host ingests live biopotential packets via public REST API (POST /api/telemetry) and broadcasts them worldwide via Server-Sent Events (SSE).',
    technicalDetails: [
      'Worldwide cloud ingestion via public REST endpoint (POST /api/telemetry)',
      'Sub-20 ms low-latency Server-Sent Events (SSE) telemetry stream to all browsers',
      'Native Web Bluetooth API (BLE) browser link support + localhost fallback (ws://localhost:8765)'
    ]
  },
  {
    step: '04',
    title: 'Real-Time Insights & Classification',
    subtitle: 'Prefrontal Alpha Asymmetry & Cognitive Load',
    description: 'Classified indices (Cognitive Load, Stress Index, Valence) and raw calibrated microvolt channels stream concurrently to the live oscilloscope strip-chart and analytics suite.',
    technicalDetails: [
      'Frontal Alpha Asymmetry (FAA) computed from Fp1/Fp2 differential for emotional valence',
      'Frontal Midline Theta (Fmθ) monitoring for working memory and deep focus',
      'Standardized BIDS-compliant CSV and European Data Format (EDF+) export'
    ]
  }
];

export const TECH_SPECS: SpecCategory[] = [
  {
    title: 'Electrophysiology Front-End',
    specs: [
      { label: 'Electrode Channels', value: '3 Electrodes: Fp1 (Left Frontal), Fp2 (Right Frontal), REF/GND (Earclip)' },
      { label: 'Electrode Material', value: 'Silver/Silver-Chloride (Ag/AgCl) conductive dry elastomer' },
      { label: 'Montage Standard', value: 'International 10–20 System (Bilateral Prefrontal Fp1-Fp2 Differential)' },
      { label: 'ADC Architecture', value: '24-bit Low-Power Simultaneous Sampling Delta-Sigma' },
      { label: 'Sampling Rate', value: '250 Hz / 500 Hz selectable streaming' },
      { label: 'Input Noise Floor', value: '< 0.75 µV RMS (0.1 – 50 Hz bandpass)' },
      { label: 'Input Dynamic Range', value: '± 375 mV full-scale' },
      { label: 'CMRR (Rejection)', value: '> 112 dB at 50/60 Hz mains interference' },
      { label: 'Impedance Interrogation', value: 'Continuous real-time impedance check for all 3 electrodes' }
    ]
  },
  {
    title: 'Global Host Telemetry & Ingestion Specs',
    specs: [
      { label: 'Global Ingestion Protocol', value: 'REST API (POST /api/telemetry) with JSON payload' },
      { label: 'Cloud Stream Protocol', value: 'Server-Sent Events (SSE) stream (GET /api/telemetry/stream)' },
      { label: 'Alternative Link Protocols', value: 'Web Bluetooth API (BLE) & Localhost WS (ws://localhost:8765)' },
      { label: 'Cloud Streaming Latency', value: '< 20 ms worldwide transmission' },
      { label: 'Payload Format', value: 'Biopotential stream { ch1: Fp1, ch2: Fp2, ref: REF, battery, impedance }' },
      { label: 'Session Data Export', value: '1-click BIDS/OpenBCI-compliant CSV session log export with ISO timestamps, microvolts, and impedances' },
      { label: 'Real-Time Cognitive Sentinel', value: 'Persistent cognitive alert engine with live TBR/CLI fatigue & deep focus pattern detection, UI pulse notification, and acoustic feedback' },
      { label: 'Link Status Telemetry', value: 'Live visual indicator with packet counter, latency ms, and impedance matrix' }
    ]
  },
  {
    title: 'Mechanical & Ergonomics (CAD Verified)',
    specs: [
      { label: 'CAD File Availability', value: 'Native STEP, STL, DXF 3D assembly models available' },
      { label: 'Chassis Material', value: 'Biocompatible polyamide-12 + Beta-Titanium memory alloy' },
      { label: 'Total Weight', value: '36.5 grams (Ultralight 3-electrode chassis)' },
      { label: 'Head Size Fitment', value: 'Circumference 52 cm to 62 cm (Self-adjusting flexure)' },
      { label: 'Ingress Protection', value: 'IP54 sweat and moisture resistance' }
    ]
  },
  {
    title: 'Power & Storage',
    specs: [
      { label: 'Battery Capacity', value: '240 mAh Lithium-Polymer cell' },
      { label: 'Continuous Run Time', value: '16.5 hours continuous 3-channel streaming' },
      { label: 'Charging Method', value: 'Magnetic pogo-pin dock (100% in 40 minutes)' },
      { label: 'Local Backup Storage', value: 'On-board flash logging buffer' }
    ]
  }
];

export const USE_CASES: UseCase[] = [
  {
    tag: 'INDIVIDUAL // FOCUS & RECOVERY',
    title: 'Attentional Load & Cognitive Fatigue Prevention',
    audience: 'High-output engineers, writers, knowledge workers, biohackers',
    challenge: 'Subjective feeling is a notoriously flawed indicator of mental fatigue. Knowledge workers push through acute cognitive degradation, triggering long recovery cycles and diminished error-checking.',
    solution: 'Kortex-Kare continuously tracks prefrontal theta/alpha power ratios. When executive working memory saturates, subtle micro-prompts signal the optimal 5-minute break before irreversible burnout occurs.',
    metrics: ['+34% Sustained Daily Deep Focus', 'Real-time Cognitive Load Index', 'Zero Gel Prep']
  },
  {
    tag: 'RESEARCH // ACADEMIA',
    title: 'Ecological Neuroscience & Open BCI Pipelines',
    audience: 'Cognitive psychologists, neuroscientists, BCI engineers',
    challenge: 'Conventional research EEG requires 45 minutes of gel application in soundproof Faraday cages, restricting ecological validity and natural subject interaction.',
    solution: 'Deploy 3 dry prefrontal leads anywhere with immediate 500 Hz Lab Streaming Layer (LSL) transmission. Interoperates natively with Python MNE, MATLAB EEGLAB, PsychoPy, and OpenBCI tools.',
    metrics: ['Native LSL Timestamp Sync', '< 1 µV Noise Floor', 'Raw EDF+ / BIDS Export']
  },
  {
    tag: 'ENTERPRISE // OPERATIONAL SAFETY',
    title: 'Occupational Vigilance & Cognitive Ergonomics',
    audience: 'Aviation operators, surgical teams, corporate wellness programs',
    challenge: 'Critical operator vigilance drops precipitously after continuous surveillance shifts, increasing human-error liability in high-stakes environments.',
    solution: 'Real-time neurological telemetry across teams monitors objective drowsiness (delta intrusions), mental overload spikes, and sympathetic nervous system agitation without intrusive tests.',
    metrics: ['Objective Drowsiness Warnings', 'Continuous Shift Telemetry', 'Multi-Unit Dashboard']
  }
];
